# Generated by Django 3.0.3 on 2020-06-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_applications_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='applicationDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default=False, max_length=10),
        ),
    ]
