# Generated by Django 3.0.3 on 2020-05-14 22:26

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ilan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirketPoster', models.ImageField(blank=True, upload_to='images/')),
                ('email', models.CharField(max_length=150)),
                ('ilanBaslik', models.CharField(max_length=255)),
                ('konum', models.CharField(max_length=255)),
                ('isKonum', models.ImageField(blank=True, upload_to='images/')),
                ('isturu', models.FloatField()),
                ('calismaZamani', models.CharField(choices=[('Part Time', 'Yarı Zamanlı'), ('Full Time', 'Tam Zamanlı')], max_length=10)),
                ('isTanimi', ckeditor_uploader.fields.RichTextUploadingField()),
                ('sirketIsmi', models.CharField(max_length=150)),
                ('etiketAlani', models.CharField(blank=True, max_length=150)),
                ('sirketTanimi', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('sirketWebsite', models.CharField(blank=True, max_length=150)),
                ('sirketFacebook', models.CharField(blank=True, max_length=150)),
                ('sirketTwitter', models.CharField(blank=True, max_length=150)),
                ('sirketLinkedin', models.CharField(blank=True, max_length=150)),
                ('sirketLogo', models.ImageField(blank=True, upload_to='images/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
