# Generated by Django 3.0.3 on 2020-05-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isIlan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ilan',
            old_name='isturu',
            new_name='isTuru',
        ),
    ]
