# Generated by Django 3.0.3 on 2020-05-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isIlan', '0003_remove_ilan_iskonum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='ilanBaslik',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='isTuru',
            field=models.CharField(choices=[('Part Time', 'Yarı Zamanlı'), ('Full Time', 'Tam Zamanlı')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='konum',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='sirketFacebook',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='sirketIsmi',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='sirketLinkedin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='sirketTwitter',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='sirketWebsite',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
