# Generated by Django 3.0.3 on 2020-05-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isIlan', '0004_auto_20200515_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='calismaZamani',
            field=models.CharField(blank=True, choices=[('Part Time', 'Yarı Zamanlı'), ('Full Time', 'Tam Zamanlı')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='isTuru',
            field=models.CharField(blank=True, choices=[('Part Time', 'Yarı Zamanlı'), ('Full Time', 'Tam Zamanlı')], max_length=10),
        ),
    ]
