# Generated by Django 3.0.3 on 2020-05-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isIlan', '0005_auto_20200515_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='calismaZamani',
            field=models.CharField(blank=True, choices=[('Zaman', 'Yarı Zamanlı'), ('Zaman', 'Tam Zamanlı')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='isTuru',
            field=models.CharField(blank=True, choices=[('Zaman', 'Yarı Zamanlı'), ('Zaman', 'Tam Zamanlı')], max_length=10),
        ),
    ]
