# Generated by Django 3.0.3 on 2020-05-25 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isIlan', '0009_auto_20200525_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='isTuru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isIlan.Category'),
        ),
    ]
