# Generated by Django 3.0.3 on 2020-05-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isIlan', '0010_auto_20200525_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
