# Generated by Django 3.0.3 on 2020-05-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isIlan', '0013_ilan_tecrube'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='personelSayisi',
            field=models.CharField(default='Belirtilmemiştir', max_length=10),
        ),
    ]
