# Generated by Django 3.0.3 on 2020-05-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isIlan', '0014_ilan_personelsayisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='sonBasvuru',
            field=models.DateField(default='2020-07-25'),
        ),
    ]
