# Generated by Django 3.0.3 on 2020-06-03 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('isIlan', '0018_remove_ilan_sirkettanimi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
