# Generated by Django 3.0.3 on 2020-06-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isIlan', '0022_auto_20200603_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
