# Generated by Django 3.0.3 on 2020-06-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isIlan', '0024_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rate',
        ),
    ]
