# Generated by Django 3.0.3 on 2020-03-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_setting_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='adaysayisi',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='setting',
            name='companyname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='setting',
            name='paylasilanissayisi',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='setting',
            name='sirketsayisi',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='setting',
            name='trendingkey1',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='setting',
            name='trendingkey2',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='setting',
            name='trendingkey3',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='setting',
            name='yerlestirileniscisayisi',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
