# Generated by Django 3.0.3 on 2020-04-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200331_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='highlight_index',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
