# Generated by Django 3.0.3 on 2020-04-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_setting_highlight_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='highlight_about',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='setting',
            name='highlight_blog',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='setting',
            name='highlight_blogSingle',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='setting',
            name='highlight_contact',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='setting',
            name='highlight_faq',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='setting',
            name='highlight_gallery',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='setting',
            name='highlight_jobListings',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='setting',
            name='highlight_jobSingle',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='setting',
            name='highlight_login',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='setting',
            name='highlight_portfolio',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='setting',
            name='highlight_portfolioSingle',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='setting',
            name='highlight_postJob',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='setting',
            name='highlight_serviceSingle',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='setting',
            name='highlight_services',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='setting',
            name='highlight_testimonials',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
