# Generated by Django 3.0.3 on 2020-04-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200425_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='ozgecmisSayisi',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='setting',
            name='uyeSirketSayisi',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
