# Generated by Django 3.0.3 on 2020-05-15 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
