# Generated by Django 3.0.3 on 2020-05-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200524_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='aboutus2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='aboutus',
            field=models.TextField(blank=True),
        ),
    ]
