# Generated by Django 3.0.3 on 2020-05-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200525_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='youtubeLink',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='youtubeLink2',
            field=models.TextField(blank=True),
        ),
    ]
