# Generated by Django 3.0.3 on 2020-05-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200525_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='youtubeLink',
            new_name='aboutusLink',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='youtubeLink2',
            new_name='aboutusLink2',
        ),
    ]
