# Generated by Django 3.0.3 on 2020-05-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20200525_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='aboutusPicture',
            field=models.ImageField(blank=True, upload_to='images/aboutus'),
        ),
        migrations.AddField(
            model_name='setting',
            name='aboutusPicture2',
            field=models.ImageField(blank=True, upload_to='images/aboutus'),
        ),
    ]
