# Generated by Django 3.0.3 on 2020-06-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20200602_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cv',
            field=models.FileField(blank=True, default='cv/default.pdf', upload_to='cv/'),
        ),
    ]
